[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "netmanage"
version = "0.1.0"
description = "Net-Manage for network management."

[tool.setuptools.packages.find]
include = ["netmanage*"]
