- name: Cisco IOS Run Arbitrary Commands Playbook
  gather_facts: no
  hosts: "{{ host_group }}"
  order: sorted

  tasks:

    - name: run "{{ commands }}" on remote devices
      connection: network_cli
      cisco.ios.ios_command:
        commands: "{{ commands }}"
      vars:
        ansible_command_timeout: "{{ ansible_timeout | default('30') }}"
        ansible_network_os: cisco.ios.ios