- name: Cisco NXOS Run Arbitrary Commands Playbook
  gather_facts: no
  hosts: "{{ host_group }}"

  tasks:

    - name: run "{{ commands }}" on remote devices
      # when: inventory_hostname == "{{ host_name }}"
      connection: network_cli
      cisco.nxos.nxos_command:
        commands: "{{ commands }}"
      vars:
        ansible_command_timeout: "{{ ansible_timeout | default('30') }}"
        ansible_network_os: cisco.nxos.nxos