- name: Gather Facts from Cisco ASA Devices
  gather_facts: no
  hosts: "{{ host_group }}"
  order: sorted
  connection: network_cli
  vars:
    gather_info: "{{ gather_info }}"
    subset: "{{ gather_info.subset | default([]) }}"
    network_subset: "{{ gather_info.network_subset | default([]) }}"

  tasks:

    - name: Gather ASA Facts
      cisco.asa.asa_facts:
        gather_subset: "{{ subset }}"
        gather_network_resources: "{{ network_subset }}"
      vars:
        ansible_command_timeout: "{{ ansible_timeout | default('30') }}"
