- name: Cisco NXOS Show Interface Playbook
  gather_facts: no
  hosts: "{{ host_group }}"

  tasks:

    - name: run show interface on remote devices
      connection: network_cli
      cisco.nxos.nxos_command:
        commands: show interface
      vars:
        ansible_command_timeout: "{{ ansible_timeout | default('240') }}"
