- name: Get F5 sync status
  gather_facts: no
  hosts: "{{ host_group }}"
  

  tasks:
    - name: creating UCS backup on remote devices
      f5networks.f5_modules.bigip_command:
        commands:
          - "{{ command }}"
        provider:
          user: "{{ user }}"
          server: "{{ ansible_host }}"
          password: "{{ password }}"
          server_port: "{{ ansible_port }}"
          validate_certs: "{{ validate_certs }}"
      delegate_to: localhost
      vars:
        ansible_command_timeout: "{{ ansible_timeout | default('240') }}"