- name: F5 Execute Read-only Command
  gather_facts: no
  hosts: "{{ host_group }}"
  

  tasks:
    - name: run "{{ command }}" on remote devices
      f5networks.f5_modules.bigip_command:
        commands:
          - "{{ command }}"
        provider:
          user: "{{ user }}"
          server: "{{ ansible_host }}"
          password: "{{ password }}"
          server_port: "{{ ansible_port | default('443') }}"
          validate_certs: "{{ validate_certs | default('yes') }}"
      delegate_to: localhost
      vars:
        ansible_command_timeout: "{{ ansible_timeout | default('240') }}"