- name: Get F5 VLANs
  gather_facts: no
  hosts: "{{ host_group }}"
  
  tasks:
    - name: get F5 VLANs on {{host_group}}
      f5networks.f5_modules.bigip_command:
        commands:
          - list net self
        provider:
          user: "{{ user }}"
          server: "{{ ansible_host }}"
          password: "{{ password }}"
          server_port: "{{ ansible_port | default('443') }}"
          validate_certs: "{{ validate_certs | default('yes')}}"
      delegate_to: localhost