- name: F5 Get VCMP Guests on Host
  gather_facts: no
  hosts: "{{ host_group }}"
  

  tasks:

    - name: list the vCMP guests on {{ host_group }}
      f5networks.f5_modules.bigip_command:
        commands: list vcmp guest
        provider:
          user: "{{ user }}"
          server: "{{ ansible_host }}"
          password: "{{ password }}"
          server_port: "{{ ansible_port }}"
          validate_certs: "{{ validate_certs }}"
      delegate_to: localhost
      vars:
        parser: generic

    - name: view vCMP guests that are in a state of provisioned or higher on {{ host_group }}
      f5networks.f5_modules.bigip_command:
        commands: show vcmp guest
        provider:
          user: "{{ user }}"
          server: "{{ ansible_host }}"
          password: "{{ password }}"
          server_port: "{{ ansible_port }}"
          validate_certs: "{{ validate_certs }}"
      delegate_to: localhost
      vars:
        parser: generic