- name: Get F5 Interface Statuses
  gather_facts: no
  hosts: "{{ host_group }}"
  
  tasks:
    - name: get F5 interface statuses on {{host_group}}
      f5networks.f5_modules.bigip_command:
        commands:
          - show net interface | grep -v "Interface\|Status\|Out\|-\\-\\-"
          - show net trunk | grep -A 2 Mbps | grep -v "Mbps\|-\\-\\-"
        provider:
          user: "{{ username }}"
          server: "{{ ansible_host }}"
          password: "{{ password }}"
          server_port: "{{ ansible_port | default('443') }}"
          validate_certs: "{{ validate_certs | default('yes')}}"
      delegate_to: localhost