- name: Get Pools and Members
  gather_facts: no
  hosts: "{{ host_group }}"
  
  tasks:
    - name: get F5 pools and members {{host_group}}
      f5networks.f5_modules.bigip_command:
        commands:
          - list ltm pool /*/* members | grep "{\|address"
        provider:
          user: "{{ username }}"
          server: "{{ ansible_host }}"
          password: "{{ password }}"
          server_port: "{{ ansible_port | default('443') }}"
          validate_certs: "{{ validate_certs | default('yes')}}"
      delegate_to: localhost