- name: Get F5 VLAN Database
  gather_facts: no
  hosts: "{{ host_group }}"
  
  tasks:
    - name: get F5 VLAN database on {{host_group}}
      f5networks.f5_modules.bigip_command:
        commands:
          - show net vlan | grep "Net::Vlan:\|Interface Name\|Tag"
        provider:
          user: "{{ username }}"
          server: "{{ ansible_host }}"
          password: "{{ password }}"
          server_port: "{{ ansible_port | default('443') }}"
          validate_certs: "{{ validate_certs | default('yes')}}"
      delegate_to: localhost