- name: Get F5 Availability and Destination
  gather_facts: no
  hosts: "{{ host_group }}"
  
  tasks:
    - name: get F5 VIP availability and destination for {{host_group}}
      f5networks.f5_modules.bigip_command:
        commands:
          - show ltm virtual /*/* | grep "Ltm::\|Availability\|State\|Reason\|Destination"
        provider:
          user: "{{ username }}"
          server: "{{ ansible_host }}"
          password: "{{ password }}"
          server_port: "{{ ansible_port | default('443') }}"
          validate_certs: "{{ validate_certs | default('yes')}}"
      delegate_to: localhost