- name: Get Pool Member availability
  gather_facts: no
  hosts: "{{ host_group }}"
  
  tasks:
    - name: get F5 Pool Member availability {{host_group}}
      f5networks.f5_modules.bigip_command:
        commands:
          - show ltm pool /*/* members detail | grep "Ltm::Pool\|Availability"
        provider:
          user: "{{ username }}"
          server: "{{ ansible_host }}"
          password: "{{ password }}"
          server_port: "{{ ansible_port | default('443') }}"
          validate_certs: "{{ validate_certs | default('yes')}}"
      delegate_to: localhost