- name: Get F5 VIP data
  gather_facts: no
  hosts: "{{ host_group }}"
  
  tasks:
    - name: get F5 VIP data {{host_group}}
      f5networks.f5_modules.bigip_command:
        commands:
          - list ltm virtual /*/* destination pool
        provider:
          user: "{{ username }}"
          server: "{{ ansible_host }}"
          password: "{{ password }}"
          server_port: "{{ ansible_port | default('443') }}"
          validate_certs: "{{ validate_certs | default('yes')}}"
      delegate_to: localhost
      vars:
        ansible_command_timeout: "{{ ansible_timeout | default('240') }}"
