- name: "{{ name | default('Palo Alto Run Adhoc Command') }}"
  hosts: "{{ host_group }}"
  connection: local
  gather_facts: no

  tasks:
    - name: executing "{{ cmd }}" on "{{ host_group }}"
      paloaltonetworks.panos.panos_op:
        cmd: "{{ cmd }}"
        cmd_is_xml: "{{ cmd_is_xml }}"
        provider:
          username: "{{ user }}"
          ip_address: "{{ ansible_host }}"
          password: "{{ password }}"
          serial_number: "{{ serial_number }}"
      delegate_to: localhost
      vars:
        ansible_command_timeout: "{{ ansible_timeout | default('240') }}"