- name: Palo Alto Get Physical Interfaces
  hosts: "{{ host_group }}"
  connection: local
  gather_facts: no

  tasks:
    - name: get physical interfaces on remote devices
      paloaltonetworks.panos.panos_op:
        cmd: show interface hardware
        cmd_is_xml: False
        provider:
          username: "{{ user }}"
          ip_address: "{{ ansible_host }}"
          password: "{{ password }}"
      delegate_to: localhost
      vars:
        ansible_command_timeout: "{{ ansible_timeout | default('240') }}"