- name: Cisco NXOS Create VRF Playbook
  gather_facts: no
  hosts: "{{ host_group }}"

  tasks:          

    - name: Create "{{ vrf_name }}" VRF
      cisco.nxos.nxos_vrf:
        name: "{{ vrf_name }}"
        description: "{{ description | default() }}"
        state: present
      vars:
        ansible_command_timeout: "{{ ansible_timeout | default('30') }}"
        ansible_connection: ansible.netcommon.network_cli

    - name: Save Running Config
      nxos_config:
        save_when: modified
      vars:
        ansible_command_timeout: "{{ ansible_timeout | default('30') }}"
        ansible_connection: ansible.netcommon.network_cli