- name: Cisco NXOS Toggle Feature Playbook
  gather_facts: no
  hosts: "{{ host_group }}"

  tasks:          

    - name: Toggle "{{ feature_name }}" feature
      cisco.nxos.nxos_feature:
        feature: "{{ feature_name }}"
        state: "{{ state }}"
      vars:
        ansible_command_timeout: "{{ ansible_timeout | default('30') }}"
        ansible_connection: ansible.netcommon.network_cli

    - name: Save Running Config
      nxos_config:
        save_when: modified
      vars:
        ansible_command_timeout: "{{ ansible_timeout | default('30') }}"
        ansible_connection: ansible.netcommon.network_cli