- name: Cisco NXOS Create VLAN Playbook
  gather_facts: no
  hosts: "{{ host_group }}"

  tasks:          
    - name: Create "{{ vlan_id }}" - "{{ vlan_name }}"
      cisco.nxos.nxos_vlans:
        config:
        - vlan_id: "{{ vlan_id }}"
          name: "{{ vlan_name }}"
          enabled: "{{ enabled }}"
        state: "{{ state }}"
      vars:
        ansible_command_timeout: "{{ ansible_timeout | default('30') }}"
        ansible_connection: ansible.netcommon.network_cli

    - name: Save Running Config
      nxos_config:
        save_when: modified
      vars:
        ansible_command_timeout: "{{ ansible_timeout | default('30') }}"
        ansible_connection: ansible.netcommon.network_cli