- name: Cisco NXOS Create VLAN Interface (SVI) Playbook
  gather_facts: no
  hosts: "{{ host_group }}"

  tasks:          
    - name: Create SVI "{{ svi_id }}"
      cisco.nxos.nxos_interfaces:
        config:
        - name: Vlan "{{ svi_id }}"
          description: {{ svi_description }}
          enabled: {{ admin_state }}
          ipv4:
          - address: {{ ip_address }}
      state: merged
        svi: "{{ svi_id }}"
        description: "{{ svi_description }}"
        ip_address: "{{ ip_address }}"
        state: present
        admin_state: "{{ admin_state }}"
      vars:
        ansible_command_timeout: "{{ ansible_timeout | default('30') }}"
        ansible_connection: ansible.netcommon.network_cli

    - name: Save Running Config
      nxos_config:
        save_when: modified
      vars:
        ansible_command_timeout: "{{ ansible_timeout | default('30') }}"
        ansible_connection: ansible.netcommon.network_cli