- name: F5 Configure DNS Settings
  gather_facts: no
  hosts: "{{ host_group }}"


  tasks:

    - name: configure DNS settings
      f5networks.f5_modules.bigip_device_dns:
        name_servers: "{{ name_servers }}"
        provider:
          user: "{{ user }}"
          server: "{{ ansible_host }}"
          password: "{{ password }}"
          server_port: "{{ ansible_port }}"
          validate_certs: "{{ validate_certs }}"
      delegate_to: localhost

    - name: verify DNS settings
      f5networks.f5_modules.bigip_command:
        commands:
          - list sys dns
        provider:
          user: "{{ user }}"
          server: "{{ ansible_host }}"
          password: "{{ password }}"
          server_port: "{{ ansible_port }}"
          validate_certs: "{{ validate_certs }}"
      delegate_to: localhost
    