# (Rename this file to secrets.toml before modifying it.)

# GLOBAL VARIABLES

# The name of the database to store results in.
database_name=''

# The full path to the database file location.
database_path=''

# The path to the Net-Manage repository.
netmanage_path=''

# The path to the Ansible private directory. This is the directory that
# that contains a file named 'hosts' inside a sub-directory named 'inventory'.
# See 'https://ansible.readthedocs.io/projects/runner/en/stable/intro/' for
# more information (Note: The only directory and file that must exist is
# 'inventory/hosts').
private_data_directory=''

# Whether to validate SSL certificates (True/False, not wrapped in quotes).
validate_certs=false

# CISCO ASA VARIABLES
asa_devices_username=''
asa_devices_password=''

# CISCO DNAC VARIABLES
dnac_url=''
dnac_username=''
dnac_password=''
dnac_platform_ids=''  # Case-sensitive, comma-delimited list of platform IDs (optional)

# CISCO IOS VARIABLES
ios_devices_username=''
ios_devices_password=''

# CISCO NXOS VARIABLES
nxos_devices_username=''
nxos_devices_password=''

# F5 LTM VARIABLES
f5_ltm_username=''
f5_ltm_password=''

# INFOBLOX VARIABLES
infoblox_url=''
infoblox_username=''
infoblox_password=''
infoblox_paging=true

# MERAKI VARIABLES (see end of file for less-used keyword arguments)
meraki_api_key=''
meraki_networks=''  # Required for certain collectors (otherwise optional).
meraki_organizations=''  # Required for certain collectors (otherwise optional).
meraki_macs=''  # Comma-delimited list of MACs or partial MACs (optional).

# NETBOX VARIABLES
netbox_url=''
netbox_token=''

# PALO ALTO VARIABLES
palo_alto_username=''
palo_alto_password=''

# SOLARWINDS VARIABLES
solarwinds_npm_server=''
solarwinds_npm_username=''
solarwinds_npm_password=''
solarwinds_npm_group_name=''

### LESS-FREQUENTLY USED KEYWORD ARGUMENTS ###

# DATABASE OPTIONS
# How to handle adding data when a table already exists. Valid options are
# 'fail', 'replace', 'append'. Default Pandas behavior is 'fail'. Default
# behavior for this tool is 'append'.
database_method='replace'

# Meraki **kwargs

meraki_lookback_timespan=86400  # 86,400 seconds == 1 day
meraki_per_page=1000
meraki_replace_network_appliance_vlans_table=true  # Whether to replace the
                                                    # original table for the
                                                    # 'network_appliance_vlans'
                                                    # Meraki collector.
meraki_suppress_logging=false
meraki_total_pages=-1  # Total number of pages to return (-1 returns all pages) (optional).
